--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/sreeram/Pictures/chonky-seal-os/wallpapers/wallpaper2.png"

-- Special
background="#272727"
foreground="#c9c9c9"
cursor="#c9c9c9"

-- Colors
color0="#272727"
color1="#c7c7c7"
color2="#909caa"
color3="#97a0aa"
color4="#9ea3aa"
color5="#a9a9aa"
color6="#b7b7b7"
color7="#c9c9c9"
color8="#5d5d5d"
color9="#c7c7c7"
color10="#909caa"
color11="#97a0aa"
color12="#9ea3aa"
color13="#a9a9aa"
color14="#b7b7b7"
color15="#c9c9c9"
