# Shell variables
# Generated by 'wal'
wallpaper='/home/sreeram/Pictures/chonky-seal-os/wallpapers/wallpaper2.png'

# Special
background='#272727'
foreground='#c9c9c9'
cursor='#c9c9c9'

# Colors
color0='#272727'
color1='#c7c7c7'
color2='#909caa'
color3='#97a0aa'
color4='#9ea3aa'
color5='#a9a9aa'
color6='#b7b7b7'
color7='#c9c9c9'
color8='#5d5d5d'
color9='#c7c7c7'
color10='#909caa'
color11='#97a0aa'
color12='#9ea3aa'
color13='#a9a9aa'
color14='#b7b7b7'
color15='#c9c9c9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
